services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=DEVELOPMENT
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=open
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=open
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
